[package]
name = "asn1-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
nom-supreme = "0.6.0"
serde = "1.0.132"
serde_json = "1.0.73"
insta = "1.9.0"
